sylius_grid:
    grids:
        app_admin_product_set:
            driver:
                name: doctrine/orm
                options:
                    class: "%app.model.product_set.class%"
            sorting:
                code: asc
            fields:
                code:
                    type: string
                    label: sylius.ui.code
                    sortable: ~
                name:
                    type: string
                    label: sylius.ui.name
            filters:
                search:
                    type: string
                    label: sylius.ui.search
                    options:
                        fields: [code, name]
            actions:
                main:
                    create:
                        type: create
                item:
                    update:
                        type: update
                    delete:
                        type: delete
