# This file is part of the Sylius package.
# (c) Paweł Jędrzejewski

sylius_admin:
    resource: '@SyliusAdminBundle/Resources/config/routing.yml'
    prefix: /admin

sylius_api:
    resource: '@SyliusAdminApiBundle/Resources/config/routing.yml'
    prefix: /api

sylius_shop:
    resource: '@SyliusShopBundle/Resources/config/routing.yml'
    prefix: /{_locale}
    requirements:
        _locale: ^[a-z]{2}(?:_[A-Z]{2})?$

sylius_shop_payum:
    resource: '@SyliusShopBundle/Resources/config/routing/payum.yml'

sylius_shop_default_locale:
    path: /
    methods: [GET]
    defaults:
        _controller: sylius.controller.shop.locale_switch:switchAction

_liip_imagine:
    resource: '@LiipImagineBundle/Resources/config/routing.yaml'

app_admin_api_product_set:
    prefix: /api
    resource: |
        alias: app.product_set
        section: api
    type: sylius.resource_api

app_admin_product_set:
    prefix: /admin
    resource: |
        templates: SyliusAdminBundle:Crud
        alias: app.product_set
        section: admin
        grid: app_admin_product_set
        except: ['show']
    type: sylius.resource

app_admin_product_set_publish:
    path: '/admin/product-sets/{id}/publish'
    methods: ['PUT']
    defaults:
        _controller: app.controller.product_set:applyStateMachineTransitionAction
        _sylius:
            state_machine:
                graph: app_product_set
                transition: publish
            redirect: app_admin_product_set_index

